### ISSUE TITLE
All plug-ins needed update Windows 10 Platform SDK 19041 for resolve AV in Win10 2004

### ISSUE THREAD

**Issue by VictorVG** [processhacker/plugins-extra#72] opened 2020-07-27 12:13 UTC
Source - https://github.com/VictorVG/ph/issues/2 ? also user **Vimann** in to forum.ru-board.com have Windows 10 build 19041.388 and wrote:

> Victor_VG, I have the same error with v3.0.7753.3226_RUS and the previous v3.0.7727.3200_RUS on Windows 10 2004 x64 (19041.388). But if you remove multiple plugins
> 
> DpiAwarenessExtPlugin.dll
> FirewallMonitorPlugin.dll
> FirmwarePlugin.dll
> LiveDumpPlugin.dll
> MemoryExtPlugin.dll
> NvGpuPlugin.dll
> ObjectManagerPlugin.dll
> PerfMonPlugin.dll
> PoolMonPlugin.dll
> ProductPolicyPlugin.dll
> ROTViewerPlugin.dll
> SecurityExplorer.dll
> ServiceBackupRestorePlugin.dll
> SetCriticalPlugin.dll
> TaskbarExtPlugin.dll
> TerminatorPlugin.dll
> TrustedInstallerPlugin.dll
> WaitChainPlugin.dll
> 
> , then it starts up and runs without problems.

I put together a test assembly by forcing the use of Windows SDK 10 0.19041 in the projects of these plugins. Let's see what they say, but I think it's worth adapting these plugins to use the latest SDK - I hope this will save us from mistakes.

**Comment by Biswa96** [comment] 2020-07-27 12:50
I can reproduce the issue with latest ProcessHacker master branch. If I add the plugin-extras only then the crash happens in 'Release' mode only for all architectures. I am not sure forcing Windows SDK version would be a perfect solution. This type of crash was fixed in main ProcessHacker repository with 'Improve string formatting performance' pull request by dmex. Maybe this plugin-extras repo need that kind of change.

**Comment by VictorVG** [comment] 2020-07-27 13:22
**@Biswa96**

> This type of crash was fixed in main ProcessHacker repository with 'Improve string formatting performance' pull request by dmex. Maybe this plugin-extras repo need that kind of change.

Is good idea, thanks!

**Comment by VictorVG** [comment] 2020-07-29 21:27
Possible  Process Hacker commit _[0c9848c1] 2020-07-29 11:09:45 +1000 dmex : Fix plugin import bug_ fix this problem's. I wait users feedback for close this issues.

**Comment by skipik** [comment] 2020-07-29 21:48
I confirm that [0c9848c1] 2020-07-29 11:09:45 +1000 dmex : Fix plugin import bug fixes the problem! Thanks to @dmex !

**Comment by VictorVG** [comment] 2020-07-29 21:56
Ok!, **FIXED**, I close this issues.

**Comment by VictorVG** [comment] 2020-07-30 13:11
I apologize, I was glad that **skipik** does not fall and decided that it was fixed ...:(

forum.ru-board.com users fiedback:

> **Vimann**, Sent: 15: 13 30-07-2020
> 
> Yes, v3.0.7765.3238 Git-f1c3a209 - crashes continue.
> 
> The culprit plugins
> 
> AtomTablePlugin.dll
> AvgCpuPlugin.dll
> DbgViewPlugin.dll
> DnsCachePlugin.dll
> DpiAwarenessExtPlugin.dll
> FirewallMonitorPlugin.dll
> FirmwarePlugin.dll
> LiveDumpPlugin.dll
> MemoryExtPlugin.dll
> NvGpuPlugin.dll
> ObjectManagerPlugin.dll
> PerfMonPlugin.dll
> PoolMonPlugin.dll
> ProductPolicyPlugin.dll
> ROTViewerPlugin.dll
> SecurityExplorer.dll
> ServiceBackupRestorePlugin.dll
> SetCriticalPlugin.dll
> TaskbarExtPlugin.dll
> TerminatorPlugin.dll
> TrustedInstallerPlugin.dll
> WaitChainPlugin.dll
> 
> **KLASS**, Sent: 15: 43 07-30-2020
> 
> Tried it in Hyper-V where Windows 10 Version 2004 is installed (OS Build 19041.264)
> 
> these versions:
> 
> v3.0.7715.3188
> v3.0.7758.3231
> v3.0.7764.3237
> v3.0.7765.3238
> 
> Everyone crashes on startup.
> 
> [**Dumps**](https://www.upload.ee/files/12078279/ProcessHacker_v3.0_DumpFile.zip.html).
> 
> **skipik**, Sent: 15: 47 07-30-2020
> 
> Interesting movie. And I have it fixed and does not crash, but the exact OS assembly is 19041.421.

also **truefriend-cz** ib to [**ph Crashed #2**](https://github.com/VictorVG/ph/issues/2) wrote:

> Sorry, I testet version v3.0.7764.3237 Git-54430335 and newver but problem is stayed.
> OS: Windows x64 Pro 19041.388 English - Original Windows version image from Microsoft, and update to 19041.388 build. After update to 19041.388 then get this error.

**Comment by VictorVG** [comment] 2020-07-30 14:26
**KLASS** send new crash damp v3.0.7765.3238 Git-f1c3a209 - [**ProcessHacker_RYPXWSYVGRXLIPP_DumpFile.zip**](https://github.com/processhacker/plugins-extra/files/5002046/ProcessHacker_RYPXWSYVGRXLIPP_DumpFile.zip)
. OS Windows 10.0.1941.421

![e74357695e172c77a74faa2636fd5be3](https://user-images.githubusercontent.com/906886/88934876-cd9a1080-d289-11ea-8c83-ce6b9a5eb08d.png)

**Comment by dmex** [comment] 2020-08-01 06:43
I haven't been able to reproduce the crashes. All plugins and plugins-extra load fine when testing Win7, Win8 and Win10.

@VictorVG 

The minidumps cannot be debugged because they're captured/corrupted by the mismatching dbghelp/dbgcore dlls with different versions from both system32 and the process hacker directory.

Please delete dbgcore.dll/dbghelp.dll from the process hacker directory so it can load the correct matching system version and capture the minidump with the correct symbols.

**Comment by Biswa96** [comment] 2020-08-01 07:01
The crash happens **only** when I build the plugins-extra and in Release mode, not in Debug mode. Also I test the build with v19041 (stable) and v20180 (insider) Windows SDK. How can I debug the plugins-extra in Visual Studio?

**Comment by VictorVG** [comment] 2020-08-01 11:01
Yes, in my opinion, it's easier to use a script toolkit, since you first need to build the PH itself in the release and debug configurations, then build the Plugins SDK and build plugins with it. And if the first operations are performed by CustomBuildTools.exe, which excludes the possibility of an error like "I was distracted by something and I missed the necessary operation", then the chance to allow it increases further. That is why I keep a script toolkit - let the robot remember the sequence of operations, there is less chance of confusing something. If you want, I have it here [**Process Hacker 3 build toolkit v1.12.1**](https://github.com/VictorVG/Source/releases/tag/PHTk1121) (latest) there just correct in place ./build/internal/bldfull.ps1 which manages the assembly of plugins-extra. Description of what and how it works is in the file HowToBuild.txt at the root of the tarball. If you have any ideas for improving it, then I will be glad to hear them and if we are able to implement it.

Best regards, Victor

**Comment by dmex** [comment] 2020-08-02 03:08
> build the plugins-extra and in Release mode

I don't see crashes in debug or release.

> How can I debug the plugins-extra in Visual Studio?

It's identical to the main plugins, just copy the plugins-extra directory to the same folder as the plugins directory and F5 debug.

**Comment by Biswa96** [comment] 2020-08-02 15:22
The X64 Release one crashes at PhCreateProcessWin32Ex in main.c of ProcessHacker project.

**Comment by dmex** [comment] 2020-08-03 03:46
>  crashes at PhCreateProcessWin32Ex

This is caused by software injecting code and hooking CreateProcess and UpdateProcThreadAttribute.

The API previously only accepted a single ULONG64 value but was recently changed to an Array and those hooks ignore the other values in the array _while still passing the array length_ causing the crashes because lpAttributeList is missing the array data.

The only option I have is disabling those mitigation policies which was done in the latest nightly build.

I shouldn't have to disable security features because some faulty third party product.... You should uninstall whatever software is injecting hooks on those functions because I will enable those policies again at some point in the future.

**Comment by VictorVG** [comment] 2020-08-03 03:55
Ok! I wait tester feedback.

**Comment by Biswa96** [comment] 2020-08-03 04:33
Now works fine.

**Comment by VictorVG** [comment] 2020-08-03 09:14
Big thanks!

And forum.ru-board.com users send me feedback:

> **KLASS**
> 
> > **Victor_VG**
> > 
> > In Hyper-V for 2004, the subject is now started, in the logs OS it out cleanly.
> 
> **AKRAV**
> 
> > **Victor_VG**
> > 
> > On a physical machine since 2004, 3.0.7776.3249 also has no errors.

I think that since such a phenomenon occurs, then it is probably worth putting an additional check for the correctness of the array, which would work if the API was intercepted and, if necessary, would correct the values in it. Something like a bus driver, for example, a Schmidt trigger, which, while the signal is close to a square wave, simply broadcasts it to the output, and if the fronts are flat, it forms a square wave at the output, at the same time suppressing the noise whose amplitude is below its response threshold.

**Closed as completed** 2020-08-03 09:23 UTC

**Comment by dmex** [comment] 2020-08-04 13:41
It would be good to know which applications or kernel drivers are injecting these hooks on your machines. If you ever discover what software was doing it them let me know 👍🏿

**Comment by VictorVG** [comment] 2020-08-04 16:54
Ok!, no questions. If I know then says

**Comment by umokk** [comment] 2020-08-05 10:34
Removing just _PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_ON_ from _DEFAULT_MITIGATION_POLICY_FLAGS2_ worked for me. It's not necessary to remove the setting of _DEFAULT_MITIGATION_POLICY_FLAGS2_ completely from the _UpdateProcThreadAttribute_ function call.

**Comment by dmex** [comment] 2020-08-05 13:10
@umokk 

Your case is the same problem but caused by something slightly different. Either something injected a DLL that wasn't compiled with CFG causing the crash or it just crashed the current process before the policy could be enabled.

If you wanted to identify the DLL (you don't have to but just for future reference) 

1) Remove that flag and execute Process Hacker.
2) Find ProcessHacker.exe in the processes tab.
3) Open the Properties window and select the Modules tab.
4) Add the "CF Guard" column and the "Type" column.

Look for any images of types "Mapped Image" and/or "DLL" that do not have "CF Guard" and they would be the likely culprit since there shouldn't be any non-microsoft third party DLLs loaded into Process Hacker.

You should be able to see the DLL unless it was manual mapped code. dbgview from sysinternals should also show some debug output from kernel CI complaining about failing to load the image because of the mitigation policy.

**Comment by umokk** [comment] 2020-08-05 18:48
@dmex , thank you for the elaborate instruction of how to find the cause of the problem and eliminate it. Thanks to this instruction the problem was solved. My problem was foolish enough: I built the PH plugins without CFG support. Adding the appropriate compiler setting solved the problem.
