### ISSUE TITLE
Providing a compiled version of Terminator

### ISSUE THREAD

**Issue by unforgettableid** [processhacker/plugins-extra#26] opened 2017-03-02 01:03 UTC
Hi!  I wonder if you could please provide a compiled binary version of Terminator?

P.S.  Thanks for all your work on Process Hacker and your plugins!

**Comment by dmex** [comment] 2017-03-04 02:01
I don't want to provide a compiled version since there are a number of Process Hacker users who still use Steam and Valve Corporation hasn't explained why they're permanently banning users for terminating processes using the Terminator plugin. 

Since I can't rewrite the plugin to be compatible with Steam and VAC protected processes... providing compiled versions is identical to handing out instant and lifetime Steam game account bans 👍

**Comment by L-a-n-g-o-l-i-e-r-s** [comment] 2017-03-05 01:10
@dmex , Is Terminator the only plugin or aspect which valve has handed bans out for? Just curious, I'd been using it after I compiled my own copy, everything was portable and I always close it before starting a game, I'm going to have to think on if I want to keep using that plugin now.

Your FAQ answer/forum topic on VAC I found a bit confusing, "Is Process Hacker compatible with anti-cheat software such as BattlEye, Punkbuster and Warden?
    Yes. Process Hacker is compatible with anti-cheat software except for EAC (EasyAntiCheat) and VAC (Valve Anti-cheat).

    Important information: An issue with your computer is blocking the VAC system.

    Process Hacker does not block or interfere with Valve's Anti-cheat"

but the information in the topic is mixed and it's not clear, especially with the last asked question, so you know definitively that it's only the Terminator plugin which triggers a vac flag? To be 100% crystal clear, it is a permanent ban for the Terminator plugin, nothing else? :8ball: 

Thanks for the wonderful tool! Can't imagine what the problem is on their end, pretty sad. Hopefully this makes sense, I'm super tired.

**Comment by jasonspiro** [comment] 2017-03-06 22:24
> Since I can't rewrite the plugin to be compatible with Steam and VAC protected processes... providing compiled versions is identical to handing out instant and lifetime Steam game account bans

@dmex:  I don't use Steam.  So I can use compiled versions of Terminator without consequence.

Would it be sufficient to force users to click through a "You may be permanently banned from Steam" warning screen before they download Terminator binaries?

**Comment by unforgettableid** [comment] 2017-03-06 22:27
> Since I can't rewrite the plugin to be compatible with Steam and VAC protected processes... providing compiled versions is identical to handing out instant and lifetime Steam game account bans

@dmex:  I don't use Steam.  So I can use compiled versions of Terminator without consequence.

Would it be sufficient to force users to click through a "You may be permanently banned from Steam" warning screen before they download Terminator binaries?

**Comment by unforgettableid** [comment] 2017-03-06 22:30
Related:  https://github.com/processhacker2/plugins-extra/issues/28

**Comment by dmex** [comment] 2020-11-06 23:45
compiled versions of Terminator won't be possible without resigning the driver

**Closed as completed by dmex** 2020-11-06 23:45 UTC
Labels: bug

**Comment by unforgettableid** [comment] 2020-11-10 01:22
Dear @dmex:

Maybe you could please re-sign the driver some years in the future, and then start providing compiled versions of Terminator?

Alternatively, maybe you could ship a re-signed driver along with the compiled Terminator binary?  Users might not be willing to bother compiling Terminator themselves. However, these same users might still be willing to simply reinstall one driver manually.

**Comment by dmex** [comment] 2020-11-10 04:02
> ship a re-signed driver along with the compiled Terminator

The current version will be archived here.

**Comment by destroy** [comment] 2021-11-22 20:48
Is there a binary?

**Comment by Leonard2** [comment] 2024-05-07 15:43
help?
